language: python

python:
  - "2.7"

services:
  - mysql

install:
  - CFLAGS=-O0 pip install git+https://github.com/frappe/frappe.git@develop &&
  - pip install --editable .

script: 
    cd ./test_sites/ &&
    frappe --reinstall -v test_site &&
    frappe --install_app erpnext -v test_site &&
    frappe --run_tests -v test_site --app erpnext

before_script:
  - mysql -e 'create database travis' &&
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('travis') WHERE user='travis';\nFLUSH PRIVILEGES;\n" | mysql -u root

