language: python

python:
  - "2.7"

services:
  - mysql

install:
  - sudo service mysql stop
  - sudo apt-get install python-software-properties
  - sudo apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xcbcb082a1bb943db
  - sudo add-apt-repository 'deb http://ftp.osuosl.org/pub/mariadb/repo/5.5/ubuntu precise main'
  - sudo apt-get update
  - sudo apt-get purge -y mysql-common
  - sudo apt-get install mariadb-server mariadb-common libmariadbclient-dev
  - CFLAGS=-O0 pip install git+https://github.com/frappe/frappe.git@develop &&
  - pip install --editable .

script:
    cd ./test_sites/ &&
    frappe --reinstall test_site &&
    frappe --install_app erpnext test_site --verbose &&
    frappe --request '?cmd=erpnext.setup.page.setup_wizard.setup_wizard.setup_account&currency=USD&first_name=Test&last_name=User&company_name=Wind+Power+LLC&timezone=America/New_York&company_abbr=WP&industry=Manufacturing&country=United states&fy_start_date=2014-01-01&fy_end_date=2014-12-31' test_site &&
    frappe --run_tests test_site --app erpnext

before_script:
  - mysql -e 'create database travis' &&
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('travis') WHERE user='travis';\nFLUSH PRIVILEGES;\n" | mysql -u root

